namespace Futurist.Service.Dto.Common;

public static class ServiceMessageConstants
{
    public const string RofoNotFound = "Rofo not found";
    public const string RofoDeleted = "Rofo deleted";
    public const string RofoFound = "Rofo found";
    public const string RofoMustNotBeEmpty = "Rofo must not be empty";
    public const string RofoMustBeInOneRoom = "Rofo must be in one room";
    public const string RofoRoomInvalid = "Rofo room invalid";
    public const string RofoDateInvalid = "Rofo date invalid";
    public const string RofoItemIdInvalid = "Rofo item ID invalid";
    public const string RofoQtyInvalid = "Rofo qty invalid";
    public const string RofoImported = "Rofo imported";
    public const string BomStdFound = "BomStd found";
    public const string RoomIdsFound = "Room IDs found";
    public const string MupProcessed = "Mup processed";
    public const string MupResultFound = "Mup result found";
    public const string MupProcessing = "MUP Processing Job has been queued. Please check back later.";
    public const string MupJobAlreadyInProcess = "MUP Job is already in process. Please check back later.";
    public const string RoomIdRequired = "Room ID required";
    public const string BomStdJobAlreadyInProcess = "BOM STD Job is already in process. Please check back later.";
    public const string BomStdProcessing = "BOM STD Processing Job has been queued. Please check back later.";
    public const string SummaryFgCostFound = "Summary Fg Cost found";
    public const string FgCostCalculated = "Fg Cost calculated";
    public const string FgCostCalculationFailed = "Fg Cost calculation failed";
    public const string SummaryFgCostNotFound = "Summary Fg Cost not found";
    public const string FgCostRoomIdsFound = "Fg Cost room IDs found";
    public const string FgCostRoomIdsNotFound = "Fg Cost room IDs not found";
    public const string FgCostDetailFound = "Fg Cost detail found";
    public const string FgCostDetailNotFound = "Fg Cost detail not found";
    public const string RoomIdInvalid = "Room ID invalid";
    public const string FgCostAlreadyInProcess = "Fg Cost is already in process. Please check back later.";
    public const string FgCostProcessing = "Fg Cost Calculation Job has been queued. Please check back later.";
    public const string JobMonitoringFound = "Job Monitoring found";
    public const string JobMonitoringNotFound = "Job Monitoring not found";
    public const string ExchangeRateMustNotBeEmpty = "Exchange Rate must not be empty";
    public const string ExchangeRateValidToInvalid = "Exchange Rate valid to is invalid";
    public const string ExchangeRateValidFromInvalid = "Exchange Rate valid from is invalid";
    public const string ExchangeRateCurrencyCodeInvalid = "Exchange Rate currency code is invalid";
    public const string ExchangeRateInvalid = "Exchange Rate is invalid";
    public const string ExchangeRateImported = "Exchange Rate imported";
    public const string ExchangeRateFound = "Exchange Rate found";
    public const string ExchangeRateValidFromToInvalid = "Exchange Rate valid from should be less than valid to";
    public const string MupProcessFailed = "Mup process failed";
    public const string BomStdNotFound = "BomStd not found";
    public const string BomStdProcessed = "BomStd processed";
    public const string BomStdProcessFailed = "BomStd process failed";
    public const string ItemAdjustmentListFound = "Item Adjustment List found";
    public const string ItemAdjustmentRoomIdsFound = "Item Adjustment room IDs found";
    public const string ItemAdjustmentRoomIdsNotFound = "Item Adjustment room IDs not found";
    public const string ItemAdjustmentUploaded = "Item Adjustment uploaded";
    public const string ItemAdjustmentUploadFailed = "Item Adjustment upload failed";
}